import unittest
from com.shotchart.shots.season_shots import SeasonShots
from constants import COMPETITIONS
import os
import pandas as pd


class TestSeasonShots(unittest.TestCase):
    def setUp(self) -> None:
        os.chdir(os.path.abspath(os.path.join(os.path.dirname( __file__ ), '..')))
        pd.set_option("display.max_columns", None)

    # def test_season_total_shots(self):
    #     ss = SeasonShots(COMPETITIONS.LF1, 45)
    #     self.assertEqual(ss.season_total_shots(), 19072, "ERROR(test_season_total_shots): El total de lanzamientos hechos en la temporada 45 no es correcto")
    #     ss = SeasonShots(COMPETITIONS.EUROCUP, 4)
    #     self.assertEqual(ss.season_total_shots(), 29418, "ERROR(test_season_total_shots): El total de lanzamientos hechos en la temporada 4 no es correcto")
    #
    # def test_season_total_shots_from_position(self):
    #     ss = SeasonShots(COMPETITIONS.LF1, 45)
    #     self.assertEqual(ss.season_total_shots_from_position("C3R"), 1468, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde C3R en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("ER3"), 1467, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde ER3 en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("Ce3R"), 1467, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde Ce3R en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("MBR"), 1467, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde MBR en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("MER"), 1467, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde MER en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("PR"), 1467, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde PR en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("PC"), 1467, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde PC en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("PL"), 1467, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde PL en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("MEL"), 1467, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde MEL en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("MBL"), 1467, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde MBL en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("Ce3L"), 1467, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde Ce3L en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("E3L"), 1467, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde E3L en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("C3L"), 1467, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde C3L en la temporada 45 no es correcto")
    #     ss = SeasonShots(COMPETITIONS.EUROCUP, 4)
    #     self.assertEqual(ss.season_total_shots_from_position("C3R"), 2263, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde C3R en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("ER3"), 2263, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde ER3 en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("Ce3R"), 2263, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde Ce3R en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("MBR"), 2263, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde MBR en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("MER"), 2263, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde MER en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("PR"), 2263, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde PR en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("PC"), 2263, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde PC en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("PL"), 2263, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde PL en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("MEL"), 2263, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde MEL en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("MBL"), 2263, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde MBL en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("Ce3L"), 2263, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde Ce3L en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("E3L"), 2263, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde E3L en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_from_position("C3L"), 2262, "ERROR(test_season_total_shots_from_position): El total de lanzamientos realizados desde C3L en la temporada 4 no es correcto")
    #
    # def test_season_total_scored_shots_from_position(self):
    #     ss = SeasonShots(COMPETITIONS.LF1, 45)
    #     self.assertEqual(ss.season_total_shots_scored_from_position("C3R"), 564, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde C3R en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("ER3"), 625, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde ER3 en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("Ce3R"), 565, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde Ce3R en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("MBR"), 598, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde MBR en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("MER"), 597, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde MER en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("PR"), 616, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde PR en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("PC"), 587, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde PC en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("PL"), 591, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde PL en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("MEL"), 595, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde MEL en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("MBL"), 587, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde MBL en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("Ce3L"), 525, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde Ce3L en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("E3L"), 619, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde E3L en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("C3L"), 556, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde C3L en la temporada 45 no es correcto")
    #     ss = SeasonShots(COMPETITIONS.EUROCUP, 4)
    #     self.assertEqual(ss.season_total_shots_scored_from_position("C3R"), 1343, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde C3R en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("ER3"), 1302, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde ER3 en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("Ce3R"), 1323, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde Ce3R en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("MBR"), 1288, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde MBR en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("MER"), 1337, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde MER en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("PR"), 1307, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde PR en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("PC"), 1320, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde PC en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("PL"), 1296, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde PL en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("MEL"), 1335, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde MEL en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("MBL"), 1371, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde MBL en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("Ce3L"), 1313, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde Ce3L en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("E3L"), 1316, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde E3L en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_scored_from_position("C3L"), 1317, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde C3L en la temporada 4 no es correcto")
    #
    # def test_season_total_failed_shots_from_position(self):
    #     ss = SeasonShots(COMPETITIONS.LF1, 45)
    #     self.assertEqual(ss.season_total_shots_failed_from_position("C3R"), 904, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde C3R en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("ER3"), 842, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde ER3 en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("Ce3R"), 902, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde Ce3R en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("MBR"), 869, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde MBR en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("MER"), 870, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde MER en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("PR"), 851, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde PR en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("PC"), 880, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde PC en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("PL"), 876, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde PL en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("MEL"), 872, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde MEL en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("MBL"), 880, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde MBL en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("Ce3L"), 942, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde Ce3L en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("E3L"), 848, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde E3L en la temporada 45 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("C3L"), 911, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde C3L en la temporada 45 no es correcto")
    #     ss = SeasonShots(COMPETITIONS.EUROCUP, 4)
    #     self.assertEqual(ss.season_total_shots_failed_from_position("C3R"), 920, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde C3R en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("ER3"), 961, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde ER3 en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("Ce3R"), 940, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde Ce3R en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("MBR"), 975, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde MBR en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("MER"), 926, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde MER en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("PR"), 956, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde PR en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("PC"), 943, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde PC en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("PL"), 967, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde PL en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("MEL"), 928, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde MEL en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("MBL"), 892, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde MBL en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("Ce3L"), 950, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde Ce3L en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("E3L"), 947, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde E3L en la temporada 4 no es correcto")
    #     self.assertEqual(ss.season_total_shots_failed_from_position("C3L"), 945, "ERROR(test_season_total_scored_shots_from_position): El total de lanzamientos anotados desde C3L en la temporada 4 no es correcto")

    def test_set_position(self):
        ss = SeasonShots(COMPETITIONS.LF1, 45)
        #ss.get_all_colors()
